# Generated by Django 4.2.27 on 2026-01-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0002_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusorder',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
